# Generated by Django 6.0.7 on 2026-07-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shortener", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shorturl",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
